export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SIGNOUT = "AUTH_SIGNOUT";

//PRODUCT REDUCER
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRODUCT_FETCHING_FAILED = "PRODUCT_FETCHING_FAILED";
export const GET_PRODUCT = "GET_PRODUCT";